# Generated by Django 6.0.6 on 2026-09-08 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('category', models.CharField(choices=[('WATER', 'Eau'), ('ELECTRICITY', 'Électricité'), ('AIRTIME', 'Crédit téléphone'), ('OTHER', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, verbose_name='Référence facture')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (BIF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bills.biller', verbose_name='Fournisseur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to=settings.AUTH_USER_MODEL, verbose_name='Payeur')),
            ],
            options={
                'verbose_name': 'Paiement facture',
                'verbose_name_plural': 'Paiements factures',
                'ordering': ['-created_at'],
            },
        ),
    ]
