# Generated by Django 6.0.6 on 2026-09-26 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('code', models.CharField(help_text='Ex: LUMICASH, ENOFI, EHELA', max_length=20, unique=True, verbose_name='Code opérateur')),
                ('provider_type', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Banque'), ('FINTECH', 'Fintech')], default='MOBILE_MONEY', max_length=20, verbose_name='Type')),
                ('country', models.CharField(default='BI', max_length=5, verbose_name='Pays')),
                ('currency', models.CharField(default='BIF', max_length=5, verbose_name='Devise')),
                ('api_base_url', models.URLField(blank=True, help_text="⚠️ PLACEHOLDER — À remplir avec l'URL API fournie par l'opérateur", verbose_name='URL de base API')),
                ('api_key', models.CharField(blank=True, help_text="⚠️ PLACEHOLDER — Clé API fournie par l'opérateur", max_length=255, verbose_name='Clé API')),
                ('api_secret', models.CharField(blank=True, help_text="⚠️ PLACEHOLDER — Secret API fourni par l'opérateur", max_length=255, verbose_name='Secret API')),
                ('merchant_id', models.CharField(blank=True, help_text="⚠️ PLACEHOLDER — Identifiant marchand chez l'opérateur", max_length=100, verbose_name='Merchant ID')),
                ('webhook_url', models.URLField(blank=True, help_text="URL que l'opérateur appellera pour les notifications", verbose_name='URL Webhook')),
                ('webhook_secret', models.CharField(blank=True, help_text="⚠️ PLACEHOLDER — Pour vérifier l'authenticité des callbacks", max_length=255, verbose_name='Secret Webhook')),
                ('adapter_class', models.CharField(default='apps.interop.adapters.mock_adapter.MockProviderAdapter', help_text="Chemin Python de l'adaptateur API. Ex:\n- apps.interop.adapters.lumicash_adapter.LumiCashAdapter\n- apps.interop.adapters.enofi_adapter.EnofiAdapter\n- apps.interop.adapters.ehela_adapter.EhelaAdapter", max_length=100, verbose_name='Classe adaptateur')),
                ('min_transfer', models.DecimalField(decimal_places=2, default=500, max_digits=15, verbose_name='Transfert minimum (BIF)')),
                ('max_transfer', models.DecimalField(decimal_places=2, default=5000000, max_digits=15, verbose_name='Transfert maximum (BIF)')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=1, help_text='Pourcentage de frais pour les transferts inter-opérateurs', max_digits=5, verbose_name='Frais (%)')),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais fixes (BIF)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('TESTING', 'En test'), ('INACTIVE', 'Inactif')], default='TESTING', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Opérateur Externe',
                'verbose_name_plural': 'Opérateurs Externes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence Cash Tel')),
                ('external_reference', models.CharField(blank=True, help_text="Référence retournée par l'API de l'opérateur", max_length=100, verbose_name='Référence opérateur')),
                ('external_phone', models.CharField(help_text="Numéro du compte chez l'opérateur (ex: +25762...)", max_length=20, verbose_name='Numéro externe')),
                ('direction', models.CharField(choices=[('SEND', 'Cash Tel → Opérateur (Envoi)'), ('RECEIVE', 'Opérateur → Cash Tel (Réception)')], max_length=20, verbose_name='Direction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (BIF)')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais (BIF)')),
                ('status', models.CharField(choices=[('INITIATED', 'Initié'), ('PENDING_EXTERNAL', 'En attente opérateur'), ('PROCESSING', 'En cours'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('REFUNDED', 'Remboursé')], default='INITIATED', max_length=20, verbose_name='Statut')),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text="Réponse complète de l'API pour traçabilité", verbose_name='Réponse API opérateur')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='interop.externalprovider', verbose_name='Opérateur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur Cash Tel')),
            ],
            options={
                'verbose_name': 'Transfert Externe',
                'verbose_name_plural': 'Transferts Externes',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant interne (Cash Tel)')),
                ('external_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant externe (opérateur)')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Écart (BIF)')),
                ('status', models.CharField(choices=[('MATCHED', 'Concordant'), ('MISMATCH', 'Écart détecté'), ('PENDING', 'En attente'), ('RESOLVED', 'Résolu')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('reconciled_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='interop.externalprovider', verbose_name='Opérateur')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='interop.externaltransfer', verbose_name='Transfert')),
            ],
            options={
                'verbose_name': 'Rapprochement',
                'verbose_name_plural': 'Rapprochements',
                'ordering': ['-reconciled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='externaltransfer',
            index=models.Index(fields=['user', '-initiated_at'], name='interop_ext_user_id_518a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltransfer',
            index=models.Index(fields=['provider', 'status'], name='interop_ext_provide_d5c48a_idx'),
        ),
        migrations.AddIndex(
            model_name='externaltransfer',
            index=models.Index(fields=['external_reference'], name='interop_ext_externa_7e2f7f_idx'),
        ),
    ]
