# Generated by Django 6.0.6 on 2026-09-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalprovider',
            name='fee_split_agent',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Pool agents, distribué manuellement', max_digits=5, verbose_name='Part agents (%)'),
        ),
        migrations.AddField(
            model_name='externalprovider',
            name='fee_split_platform',
            field=models.DecimalField(decimal_places=2, default=35, max_digits=5, verbose_name='Part Swisderm/CashTel (%)'),
        ),
        migrations.AddField(
            model_name='externalprovider',
            name='fee_split_provider',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Part des frais reversée à LumiCash/Enofi/eHela', max_digits=5, verbose_name='Part opérateur (%)'),
        ),
        migrations.AddField(
            model_name='externaltransfer',
            name='agent_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Part pool agents (BIF)'),
        ),
        migrations.AddField(
            model_name='externaltransfer',
            name='platform_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Part Swisderm/CashTel (BIF)'),
        ),
        migrations.AddField(
            model_name='externaltransfer',
            name='provider_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Part opérateur (BIF)'),
        ),
        migrations.AddField(
            model_name='externaltransfer',
            name='settled',
            field=models.BooleanField(default=False, verbose_name='Reversé (settlement)'),
        ),
    ]
