# Generated by Django 6.0.6 on 2026-09-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0003_externaltransfer_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UssdConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(default='*300#', help_text='Ex : *300#. Doit correspondre au code attribué par Lumitel.', max_length=20, verbose_name='Code USSD')),
                ('help_text', models.CharField(default='Cash Tel : 1 Envoyer, 2 Attente, 3 Valider.', max_length=255, verbose_name="Texte d'aide")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Code USSD',
                'verbose_name_plural': 'Code USSD',
            },
        ),
        migrations.CreateModel(
            name='UssdMenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Ex : 1, 2, 3, 4, 5, 6, 7, 8, 9, 0. La touche pilote le routage.', max_length=10, unique=True, verbose_name='Touche')),
                ('parent', models.CharField(default='root', help_text='root, plus ou compte', max_length=10, verbose_name='Menu parent')),
                ('label', models.CharField(max_length=60, verbose_name='Libellé affiché')),
                ('enabled', models.BooleanField(default=True, verbose_name='Activée')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Option menu USSD',
                'verbose_name_plural': 'Options menu USSD',
                'ordering': ['parent', 'order', 'key'],
            },
        ),
    ]
