# Generated by Django 6.0.6 on 2026-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0005_rename_enofi_enoti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalprovider',
            name='adapter_class',
            field=models.CharField(default='apps.interop.adapters.mock_adapter.MockProviderAdapter', help_text="Chemin Python de l'adaptateur API. Ex:\n- apps.interop.adapters.lumicash_adapter.LumiCashAdapter\n- apps.interop.adapters.enoti_adapter.EnotiAdapter\n- apps.interop.adapters.ehela_adapter.EhelaAdapter", max_length=100, verbose_name='Classe adaptateur'),
        ),
        migrations.AlterField(
            model_name='externalprovider',
            name='code',
            field=models.CharField(help_text='Ex: LUMICASH, ENOTI, EHELA', max_length=20, unique=True, verbose_name='Code opérateur'),
        ),
        migrations.AlterField(
            model_name='externalprovider',
            name='fee_fixed',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Frais fixes (BIF)'),
        ),
        migrations.AlterField(
            model_name='externalprovider',
            name='fee_split_provider',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Part des frais reversée à LumiCash/eNoti/eHela', max_digits=5, verbose_name='Part opérateur (%)'),
        ),
        migrations.AlterField(
            model_name='externalprovider',
            name='max_transfer',
            field=models.DecimalField(decimal_places=3, default=5000000, max_digits=18, verbose_name='Transfert maximum (BIF)'),
        ),
        migrations.AlterField(
            model_name='externalprovider',
            name='min_transfer',
            field=models.DecimalField(decimal_places=3, default=500, max_digits=18, verbose_name='Transfert minimum (BIF)'),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='agent_share',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Part pool agents (BIF)'),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Montant (BIF)'),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Frais (BIF)'),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='platform_share',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Part Swisderm/CashTel (BIF)'),
        ),
        migrations.AlterField(
            model_name='externaltransfer',
            name='provider_share',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Part opérateur (BIF)'),
        ),
        migrations.AlterField(
            model_name='reconciliationrecord',
            name='difference',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Écart (BIF)'),
        ),
        migrations.AlterField(
            model_name='reconciliationrecord',
            name='external_amount',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Montant externe (opérateur)'),
        ),
        migrations.AlterField(
            model_name='reconciliationrecord',
            name='internal_amount',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Montant interne (Cash Tel)'),
        ),
    ]
