# Generated by Django 6.0.6 on 2026-09-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Commissions (BIF)')),
                ('shop_name', models.CharField(blank=True, max_length=150, verbose_name='Nom boutique')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Agent vérifié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profil Agent',
                'verbose_name_plural': 'Profils Agents',
            },
        ),
    ]
