# Generated by Django 6.0.6 on 2026-09-26 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (BIF)')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais (BIF)')),
                ('code', models.CharField(max_length=6, unique=True, verbose_name='Code retrait')),
                ('status', models.CharField(choices=[('PENDING', 'En attente agent'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('EXPIRED', 'Expiré')], default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Demande de retrait',
                'verbose_name_plural': 'Demandes de retrait',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='agent_withd_code_d106d8_idx'), models.Index(fields=['customer', 'status'], name='agent_withd_custome_09c698_idx')],
            },
        ),
    ]
