# Generated by Django 6.0.6 on 2026-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='commission_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Commissions (BIF)'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Montant (BIF)'),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Frais (BIF)'),
        ),
    ]
