# Generated by Django 6.0.6 on 2026-09-26 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('trade_name', models.CharField(blank=True, help_text='Ex: Swisderm', max_length=200, verbose_name='Nom commercial')),
                ('sector', models.CharField(choices=[('COSMETICS', 'Cosmétiques'), ('FOOD', 'Alimentation'), ('CLOTHING', 'Habillement'), ('ELECTRONICS', 'Électronique'), ('HEALTH', 'Santé'), ('SERVICES', 'Services'), ('OTHER', 'Autre')], default='OTHER', max_length=30, verbose_name="Secteur d'activité")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='merchant_logos/', verbose_name='Logo')),
                ('nif', models.CharField(blank=True, help_text='Numéro fiscal burundais', max_length=50, verbose_name="NIF (Numéro d'Identification Fiscale)")),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse physique')),
                ('bank_name', models.CharField(blank=True, help_text='Ex: CRDB', max_length=100, verbose_name='Banque principale')),
                ('bank_account_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de compte bancaire')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Commission prélevée sur chaque vente via Cash Tel', max_digits=5, verbose_name='Taux de commission (%)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Chiffre d'affaires total (BIF)")),
                ('status', models.CharField(choices=[('PENDING', 'En attente de validation'), ('ACTIVE', 'Actif'), ('SUSPENDED', 'Suspendu')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('is_primary', models.BooleanField(default=False, help_text="True pour Swisderm (l'entreprise mère qui gère Cash Tel)", verbose_name='Entreprise principale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Propriétaire du compte marchand')),
            ],
            options={
                'verbose_name': 'Profil Marchand',
                'verbose_name_plural': 'Profils Marchands',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_share', models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage des frais reversé au partenaire', max_digits=5, verbose_name='Partage de commission (%)')),
                ('agreement_ref', models.CharField(max_length=50, unique=True, verbose_name='Référence contrat')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('EXPIRED', 'Expiré'), ('TERMINATED', 'Résilié')], default='DRAFT', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_partnerships', to='merchant.merchantprofile', verbose_name='Marchand partenaire')),
                ('primary_merchant', models.ForeignKey(help_text="L'entreprise mère qui initie le partenariat", on_delete=django.db.models.deletion.CASCADE, related_name='initiated_partnerships', to='merchant.merchantprofile', verbose_name='Marchand principal (Swisderm)')),
            ],
            options={
                'verbose_name': 'Accord de Partenariat',
                'verbose_name_plural': 'Accords de Partenariat',
                'unique_together': {('primary_merchant', 'partner_merchant')},
            },
        ),
    ]
