# Generated by Django 6.0.6 on 2026-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantprofile',
            name='total_revenue',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name="Chiffre d'affaires total (BIF)"),
        ),
    ]
