# Generated by Django 6.0.6 on 2026-09-08 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant minimum (BIF)')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant maximum (BIF)')),
                ('fee_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur des frais')),
                ('fee_type', models.CharField(choices=[('FIXED', 'Fixe (BIF)'), ('PERCENTAGE', 'Pourcentage (%)')], default='FIXED', max_length=20, verbose_name='Type de frais')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Frais',
                'verbose_name_plural': 'Grille des Frais',
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Référence')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (BIF)')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais (BIF)')),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfert P2P'), ('DEPOSIT', 'Dépôt (Cash In)'), ('WITHDRAWAL', 'Retrait (Cash Out)'), ('BILL', 'Paiement Facture')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('REVERSED', 'Annulé/Remboursé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(default=dict, help_text='Données supplémentaires JSON (ex: détails facture, agent, etc.)', verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', '-created_at'], name='transaction_sender__ce1ef1_idx'), models.Index(fields=['receiver', '-created_at'], name='transaction_receive_d402ad_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_09d7ec_idx')],
            },
        ),
    ]
