# Generated by Django 6.0.6 on 2026-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_value',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Valeur des frais'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='max_amount',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Montant maximum (BIF)'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='min_amount',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Montant minimum (BIF)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Montant (BIF)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Frais (BIF)'),
        ),
    ]
