# Generated by Django 6.0.6 on 2026-09-26 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchant', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Catégorie Produit',
                'verbose_name_plural': 'Catégories Produits',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sous-total (BIF)')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais Cash Tel (BIF)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total (BIF)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de paiement'), ('PAID', 'Payé'), ('PREPARING', 'En préparation'), ('SHIPPED', 'Expédié'), ('DELIVERED', 'Livré'), ('CANCELLED', 'Annulé'), ('REFUNDED', 'Remboursé')], default='PENDING', max_length=20, verbose_name='Statut')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Adresse de livraison')),
                ('delivery_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone livraison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='merchant.merchantprofile', verbose_name='Marchand')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='transactions.transaction', verbose_name='Transaction de paiement')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('sku', models.CharField(help_text='Code produit unique', max_length=50, unique=True, verbose_name='Référence (SKU)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix (BIF)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image produit')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stock disponible')),
                ('status', models.CharField(choices=[('ACTIVE', 'En vente'), ('OUT_OF_STOCK', 'Rupture de stock'), ('DISCONTINUED', 'Arrêté')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='merchant.merchantprofile', verbose_name='Marchand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.productcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Prix au moment de la commande', max_digits=15, verbose_name='Prix unitaire (BIF)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix total (BIF)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='shop.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de Commande',
                'verbose_name_plural': 'Lignes de Commande',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='shop_order_custome_da1929_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['merchant', 'status'], name='shop_order_merchan_1303cc_idx'),
        ),
    ]
