# Generated by Django 6.0.6 on 2026-09-30 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nom du package')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix package (BIF)')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stock packages')),
                ('status', models.CharField(choices=[('ACTIVE', 'En vente'), ('INACTIVE', 'Inactif')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='merchant.merchantprofile', verbose_name='Marchand')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.package', verbose_name='Package')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_items', to='shop.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne Package',
                'verbose_name_plural': 'Lignes Packages',
            },
        ),
    ]
