# Generated by Django 6.0.6 on 2026-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_package_packageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Frais Cash Tel (BIF)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Sous-total (BIF)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Total (BIF)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Prix total (BIF)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, help_text='Prix au moment de la commande', max_digits=18, verbose_name='Prix unitaire (BIF)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Prix package (BIF)'),
        ),
        migrations.AlterField(
            model_name='package',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Stock packages'),
        ),
        migrations.AlterField(
            model_name='packageitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Prix (BIF)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Stock disponible'),
        ),
    ]
