# Generated by Django 6.0.6 on 2026-09-08 18:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant Wallet')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Solde (BIF)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('FROZEN', 'Gelé'), ('SUSPENDED', 'Suspendu')], default='ACTIVE', max_length=20, verbose_name='Statut')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
                'ordering': ['-created_at'],
            },
        ),
    ]
