# Generated by Django 6.0.6 on 2026-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Solde (BIF)'),
        ),
    ]
