# Generated by Django 6.0.6 on 2026-09-26 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la banque')),
                ('code', models.CharField(help_text='Ex: CRDB, BCB, BANCOBU, IBB, KCB, ECOBANK', max_length=20, unique=True, verbose_name='Code banque')),
                ('swift_code', models.CharField(blank=True, max_length=20, verbose_name='Code SWIFT')),
                ('country', models.CharField(default='BI', max_length=5, verbose_name='Pays')),
                ('api_base_url', models.URLField(blank=True, help_text="⚠️ PLACEHOLDER — À remplir avec l'URL API fournie par la banque", verbose_name='URL de base API')),
                ('api_key', models.CharField(blank=True, help_text='⚠️ PLACEHOLDER — Clé API fournie par la banque (à stocker chiffré en prod)', max_length=255, verbose_name='Clé API')),
                ('api_secret', models.CharField(blank=True, help_text='⚠️ PLACEHOLDER — Secret API fourni par la banque', max_length=255, verbose_name='Secret API')),
                ('webhook_secret', models.CharField(blank=True, help_text='⚠️ PLACEHOLDER — Pour vérifier les notifications de la banque', max_length=255, verbose_name='Secret Webhook')),
                ('adapter_class', models.CharField(default='apps.banking.adapters.mock_adapter.MockBankAdapter', help_text="Chemin Python de l'adaptateur API. Ex: apps.banking.adapters.crdb_adapter.CRDBAdapter", max_length=100, verbose_name='Classe adaptateur')),
                ('min_transfer', models.DecimalField(decimal_places=2, default=1000, max_digits=15, verbose_name='Transfert minimum (BIF)')),
                ('max_transfer', models.DecimalField(decimal_places=2, default=10000000, max_digits=15, verbose_name='Transfert maximum (BIF)')),
                ('daily_limit', models.DecimalField(decimal_places=2, default=50000000, max_digits=15, verbose_name='Limite journalière (BIF)')),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('TESTING', 'En test'), ('INACTIVE', 'Inactif')], default='TESTING', max_length=20, verbose_name='Statut')),
                ('is_default', models.BooleanField(default=False, help_text='True pour CRDB (banque principale de Swisderm)', verbose_name='Banque par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banque Partenaire',
                'verbose_name_plural': 'Banques Partenaires',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=50, verbose_name='Numéro de compte')),
                ('account_name', models.CharField(max_length=200, verbose_name='Nom du titulaire')),
                ('account_type', models.CharField(choices=[('PERSONAL', 'Personnel'), ('BUSINESS', 'Entreprise')], default='PERSONAL', max_length=20, verbose_name='Type de compte')),
                ('verification_status', models.CharField(choices=[('PENDING', 'En attente de vérification'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=20, verbose_name='Statut vérification')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Compte principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Titulaire')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banking.bankpartner', verbose_name='Banque')),
            ],
            options={
                'verbose_name': 'Compte Bancaire',
                'verbose_name_plural': 'Comptes Bancaires',
                'unique_together': {('bank', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence Cash Tel')),
                ('bank_reference', models.CharField(blank=True, help_text="Référence retournée par l'API de la banque", max_length=100, verbose_name='Référence banque')),
                ('direction', models.CharField(choices=[('DEPOSIT', 'Banque → Wallet (Dépôt)'), ('WITHDRAW', 'Wallet → Banque (Retrait)')], max_length=20, verbose_name='Direction')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant (BIF)')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais (BIF)')),
                ('status', models.CharField(choices=[('INITIATED', 'Initié'), ('PENDING_BANK', 'En attente banque'), ('PROCESSING', 'En cours de traitement'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('CANCELLED', 'Annulé')], default='INITIATED', max_length=20, verbose_name='Statut')),
                ('bank_response', models.JSONField(blank=True, default=dict, help_text="Réponse complète de l'API bancaire pour traçabilité", verbose_name='Réponse API banque')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='banking.bankaccount', verbose_name='Compte bancaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transfert Bancaire',
                'verbose_name_plural': 'Transferts Bancaires',
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['user', '-initiated_at'], name='banking_ban_user_id_907996_idx'), models.Index(fields=['status'], name='banking_ban_status_2bc442_idx')],
            },
        ),
    ]
