# Generated by Django 6.0.6 on 2026-09-26 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankFloat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceiling', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Plafond cantonné (BIF)')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='float_ceiling', to='banking.bankpartner', verbose_name='Banque')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Déclaré par')),
            ],
            options={
                'verbose_name': 'Plafond cantonné',
                'verbose_name_plural': 'Plafonds cantonnés',
            },
        ),
    ]
