# Generated by Django 6.0.6 on 2026-09-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_bankfloat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankfloat',
            name='ceiling',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18, verbose_name='Plafond cantonné (BIF)'),
        ),
        migrations.AlterField(
            model_name='bankpartner',
            name='daily_limit',
            field=models.DecimalField(decimal_places=3, default=50000000, max_digits=18, verbose_name='Limite journalière (BIF)'),
        ),
        migrations.AlterField(
            model_name='bankpartner',
            name='max_transfer',
            field=models.DecimalField(decimal_places=3, default=10000000, max_digits=18, verbose_name='Transfert maximum (BIF)'),
        ),
        migrations.AlterField(
            model_name='bankpartner',
            name='min_transfer',
            field=models.DecimalField(decimal_places=3, default=1000, max_digits=18, verbose_name='Transfert minimum (BIF)'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=18, verbose_name='Montant (BIF)'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Frais (BIF)'),
        ),
    ]
